default: &default
  appid: "wxb121bb800df09aa1"
  secret: "ce4a5a9bb4a8cfc5ddd736a5d1f8acc2"
  token:  "tzr"
  access_token: "/Users/Alex/accesstoken"

production: 
  appid: <%= ENV['WECHAT_APPID'] %>
  secret: <%= ENV['WECHAT_APP_SECRET'] %>
  token:   <%= ENV['WECHAT_TOKEN'] %>
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>

staging: 
  <<: *default

development: 
  <<: *default

test: 
  <<: *default